#!/bin/bash

# 데이터베이스 마이그레이션 실행 스크립트

echo "🚀 Type & Attribute 테이블 마이그레이션 시작..."
echo ""
echo "⚠️  주의: 이 스크립트는 다음 변경을 수행합니다:"
echo "  - Type 테이블: type → name, name → description, description 제거"
echo "  - Attribute 테이블: key → name"
echo ""
echo "데이터는 보존되지만, 실수를 방지하기 위해 Supabase Dashboard에서 수동 실행을 권장합니다."
echo ""
echo "==== 실행 방법 ===="
echo ""
echo "방법 1: Supabase SQL Editor (권장)"
echo "  1. https://supabase.com/dashboard 접속"
echo "  2. 프로젝트 선택"
echo "  3. SQL Editor 메뉴 클릭"
echo "  4. New Query 클릭"
echo "  5. 아래 파일 내용을 복사 & 붙여넣기:"
echo "     prisma/migrations/rename_type_and_attribute_columns.sql"
echo "  6. Run 버튼 클릭"
echo ""
echo "방법 2: 전체 재초기화 (개발 환경, 데이터 삭제됨!)"
echo "  1. Supabase SQL Editor에서 실행:"
echo "     prisma/init-v2.sql"
echo "  2. npx prisma generate"
echo "  3. npm run dev 재시작"
echo ""
echo "==== 마이그레이션 파일 경로 ===="
echo "  - prisma/migrations/rename_type_and_attribute_columns.sql (기존 데이터 보존)"
echo "  - prisma/init-v2.sql (전체 재초기화)"
echo ""

